#!/bin/bash

set -o errexit
set -o nounset

# -----------------------------------------------------------------------------

rm -f './celerybeat.pid'
exec watchfiles \
  --filter python celery.__main__.main \
  --args '-A config.celery.config beat -l INFO --pidfile='"${TEMP_DIR}/${CELERY_BEAT_LIVENESS_FILE}"''
