#!/bin/bash

set -e
set -o pipefail
set -o nounset

# -----------------------------------------------------------------------------

if command -v mongosh &> /dev/null; then
  mongo_command="mongosh"
else
  mongo_command="mongo"
fi

ping_result=$(echo 'db.runCommand("ping").ok' | ${mongo_command} localhost:27017/test --quiet 2>&1)
ping_status=$?

if [ "$ping_status" -eq 0 ] && [ "$ping_result" -eq 1 ]; then
  echo "MongoDB is healthy!"
  exit 0
else
  echo "MongoDB is unhealthy!"
  echo "Error: $ping_result"  # Print the error message if needed
  exit 1
fi
